# Generated by Django 5.1 on 2024-08-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Practicas',
            new_name='Practica',
        ),
    ]
