# Generated by Django 5.1 on 2024-08-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autorizaciones', '0004_alter_afiliado_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afiliado',
            name='dni',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='afiliado',
            name='email',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
